/*
This computer program, as defined in the Copyright, Designs and Patents Act 1998 and the Software Directive (2009/24/EC), 
is the copyright of Logic Valley Ltd, a wholly owned subsidiary of Marston (Holdings) Ltd. All rights are reserved.
*/

export const accessibilitydata = {
  fontsize: [
    '--default-FontSize',
    '--heading-FontSize',
    '--subHeading-FontSize',
    '--label-FontSize',
    '--listHeader-FontSize',
    '--mainheading-FontSize',
  ],
  fontcolor: [
    '--default-FontColour',
    '--label-FontColour',
    '--ToolbarTextColour',
    '--footer-default-fontcolor',
    '--controllabel-colour',
  ],
  titlefontcolor: [
    '--heading-FontColour',
    '--subHeading-FontColour',
    '--listHeader-FontColour',
    '--ListHeaderText-Colour',
    '--TitleBar-TextColour',
  ],
  bgcolor: [
    '--ToolbarBackgroundColour',
    '--navbar-color',
    '--navbar-group-color',
    '--titlebar-color',
    '--appcontent-bg-color',
    '--footer-color',
    '--gridbgcolor',
    '--accssibility-selected-bgcolor-pallet',
  ],
  letterspace: ['--font-letter-space'],
  lineheight: ['--text-line-height'],
  divtags: ['div', 'span', 'a', 'input', 'label', 'textarea', 'button'],
  contentscale: [
    '--default-FontSize',
    '--heading-FontSize',
    '--subHeading-FontSize',
    '--label-FontSize',
    '--listHeader-FontSize',
    '--mainheading-FontSize',
  ],
  darkcontrast: [
    '--default-FontColour',
    '--label-FontColour',
    '--ToolbarTextColour',
    '--footer-default-fontcolor',
    '--heading-FontColour',
    '--subHeading-FontColour',
    '--listHeader-FontColour',
    '--ListHeaderText-Colour',
    '--TitleBar-TextColour',
    '--ToolbarBackgroundColour',
    '--navbar-color',
    '--navbar-group-color',
    '--titlebar-color',
    '--appcontent-bg-color',
    '--footer-color',
    '--controlscolor',
    '--controllabel-colour',
  ],
  darkcontrast_bgcolor: [
    '--ToolbarBackgroundColour',
    '--navbar-color',
    '--navbar-group-color',
    '--titlebar-color',
    '--appcontent-bg-color',
    '--footer-color',
    '--gridbgcolor',
    '--tab-selected-bg-color',
  ],
  lightcontrast: [
    '--default-FontColour',
    '--label-FontColour',
    '--ToolbarTextColour',
    '--footer-default-fontcolor',
    '--heading-FontColour',
    '--subHeading-FontColour',
    '--listHeader-FontColour',
    '--ListHeaderText-Colour',
    '--TitleBar-TextColour',
    '--ToolbarBackgroundColour',
    '--navbar-color',
    '--navbar-group-color',
    '--titlebar-color',
    '--appcontent-bg-color',
    '--footer-color',
    '--controlscolor',
    '--controllabel-colour',
  ],
  lightcontrast_bgcolor: [
    '--ToolbarBackgroundColour',
    '--navbar-color',
    '--navbar-group-color',
    '--titlebar-color',
    '--appcontent-bg-color',
    '--footer-color',
    '--gridbgcolor',
    '--tab-selected-bg-color',
  ],
}
